<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CmsUserExt\Acl\UserActionAssertion'                  => __DIR__ . '/src/Acl/UserActionAssertion.php',
    'CmsUserExt\Factory\Acl\UserActionAssertionFactory'   => __DIR__ . '/src/Factory/Acl/UserActionAssertionFactory.php',
    'CmsUserExt\Factory\Controller\UserControllerFactory' => __DIR__ . '/src/Factory/Controller/UserControllerFactory.php',
    'CmsUserExt\Mapping\MetadatableInterface'             => __DIR__ . '/src/Mapping/MetadatableInterface.php',
    'CmsUserExt\Mapping\MetadataInterface'                => __DIR__ . '/src/Mapping/MetadataInterface.php',
    'CmsUserExt\Mapping\Traits\MetadatableTrait'          => __DIR__ . '/src/Mapping/Traits/MetadatableTrait.php',
    'CmsUserExt\Module'                                   => __DIR__ . '/src/Module.php',
    'CmsUserExt\Mvc\Controller\AdminController'           => __DIR__ . '/src/Mvc/Controller/AdminController.php',
    'CmsUserExt\Mvc\Controller\UserController'            => __DIR__ . '/src/Mvc/Controller/UserController.php',
    'CmsUserExtTest\Framework\TestCase'                   => __DIR__ . '/tests/Framework/TestCase.php',
    'CmsUserExtTest\SampleTest'                           => __DIR__ . '/tests/SampleTest.php',
);
