<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CmsUserExt\Mapping\MetadatableInterface'    => __DIR__ . '/src/Mapping/MetadatableInterface.php',
    'CmsUserExt\Mapping\MetadataInterface'       => __DIR__ . '/src/Mapping/MetadataInterface.php',
    'CmsUserExt\Mapping\Traits\MetadatableTrait' => __DIR__ . '/src/Mapping/Traits/MetadatableTrait.php',
    'CmsUserExt\Module'                          => __DIR__ . '/src/Module.php',
    'CmsUserExt\Mvc\Controller\AdminController'  => __DIR__ . '/src/Mvc/Controller/AdminController.php',
    'CmsUserExt\Mvc\Controller\UserController'   => __DIR__ . '/src/Mvc/Controller/UserController.php',
    'CmsUserExtTest\Framework\TestCase'          => __DIR__ . '/tests/Framework/TestCase.php',
    'CmsUserExtTest\SampleTest'                  => __DIR__ . '/tests/SampleTest.php',
);
