<?php 
/**
 * CoolMS2 User extensions module (http://www.coolms.com/)
 * 
 * @link      http://github.com/coolms/CmsUserExt for the canonical source repository
 * @copyright Copyright (c) 2006-2015 Altgraphic, ALC (http://www.altgraphic.com)
 * @license   http://www.coolms.com/license/new-bsd New BSD License
 * @author    Dmitry Popov <d.popov@altgraphic.com>
 */

namespace CmsUserExt;

$this->fieldset = $this->form->get('user')->get('extMetadata');

?>
<?= $this->render('cms-user-ext/metadata/form');
